# Test your FastAPI endpoints

GET http://localhost:8000/
Accept: application/json

###

GET http://localhost:8000/users
Accept: application/json

###
POST http://localhost:8000/users
Accept: application/json

###
DELETE http://localhost:8000/users
Accept: application/json  #Este encabezado(header) indica que se espera una respuesta a la petición en formato JSON.